services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    image: bh-${NODE_ENV}
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - ${NODE_ENV}_default
    labels:
      - "traefik.enable=true"
      # HTTPS Route
      - "traefik.http.routers.${NODE_ENV}-app-secure.rule=${HOST}"
      - "traefik.http.routers.${NODE_ENV}-app-secure.entrypoints=websecure"
      - "traefik.http.routers.${NODE_ENV}-app-secure.middlewares=strip-${TAG}"
      - "traefik.http.routers.${NODE_ENV}-app-secure.tls.certresolver=myresolver"
      - "traefik.http.services.${NODE_ENV}-app.loadbalancer.server.port=3000"
 #     - "traefik.http.routers.${NODE_ENV}-app.middlewares=auth"
#      - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$sdARNjrF$$o5oY9am2uedUdHztBJUOn1"

      # HTTP Route
      - "traefik.http.routers.${NODE_ENV}-app.rule=${HOST}"
      - "traefik.http.routers.${NODE_ENV}-app.entrypoints=web"
      - "traefik.http.services.${NODE_ENV}-app.loadbalancer.server.port=3000"
      - "traefik.http.routers.${NODE_ENV}-app.middlewares=strip-${TAG}"
      - "traefik.http.middlewares.strip-${TAG}.stripPrefix.prefixes=/${TAG}"

    
  db:
    image: mysql:8.0
    restart: always
    networks:
      - ${NODE_ENV}_default
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_PORT: ${MYSQL_DB_PORT}
      MYSQL_HOST: ${MYSQL_DB_HOST}
    labels:
      - "traefik.enable=false"
    volumes:
      - ${NODE_ENV}_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
    ports:
      - "8091:80"
    networks:
      - ${NODE_ENV}_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=PathPrefix(`/db`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.middlewares=strip-db"
      - "traefik.http.middlewares.strip-db.stripprefix.prefixes=/db"

  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    # network_mode: "host"
    networks:
      - ${NODE_ENV}_default
    depends_on:
      redis:
        condition: service_started
    # labels:
    #   - "traefik.enable=true"
      
    #   # LiveKit WebSocket (7880)
    #   - "traefik.http.routers.livekit.rule=Host(`livekit.navigo.et`)"
    #   - "traefik.http.routers.livekit.entrypoints=websecure"
    #   - "traefik.http.routers.livekit.tls=true"
    #   - "traefik.http.routers.livekit.tls.certresolver=myresolver"
    #   - "traefik.http.services.livekit.loadbalancer.server.port=7880"

    #   # WHIP/WHEP over HTTP (8080)
    #   - "traefik.http.routers.livekitwhip.rule=Host(`livekit-whip.navigo.et`)"
    #   - "traefik.http.routers.livekitwhip.entrypoints=websecure"
    #   - "traefik.http.routers.livekitwhip.tls=true"
    #   - "traefik.http.routers.livekitwhip.tls.certresolver=myresolver"
    #   - "traefik.http.services.livekitwhip.loadbalancer.server.port=8080"

    #   - "traefik.http.middlewares.websocket.headers.customrequestheaders.Connection=Upgrade"
    #   - "traefik.http.middlewares.websocket.headers.customrequestheaders.Upgrade=websocket"

    volumes:
      - ./livekit/livekit.yaml:/etc/livekit.yaml

  redis:
    image: redis:7-alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    # network_mode: "host"
    networks:
      - ${NODE_ENV}_default
    volumes:
      - ./livekit/redis.conf:/etc/redis.conf

  egress:
    image: livekit/egress:latest
    restart: unless-stopped
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
    # network_mode: "host"
    networks:
      - ${NODE_ENV}_default
    volumes:
      - ./livekit/egress.yaml:/etc/egress.yaml
    cap_add:
      - CAP_SYS_ADMIN

  ingress:
    image: livekit/ingress:latest
    restart: unless-stopped
    environment:
      - INGRESS_CONFIG_FILE=/etc/ingress.yaml
    network_mode: "host"
    # networks:
    #   - ${NODE_ENV}_default
    volumes:
      - ./livekit/ingress.yaml:/etc/ingress.yaml

  # turnserver:
  #   image: coturn/coturn  # Or the actual image you're using
  #   command: turnserver -c /etc/turnserver.conf
  #   networks:
  #     - ${NODE_ENV}_default
    # ports:
    #   - "5349:5349"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.tcp.routers.turn.rule=HostSNI(`turn.navigo.et`)"
  #     - "traefik.tcp.routers.turn.entrypoints=websecure"
  #     - "traefik.tcp.routers.turn.tls=true"
  #     - "traefik.tcp.routers.turn.tls.certresolver=myresolver"
  #     - "traefik.tcp.services.turn.loadbalancer.server.port=5349"


