services:
  app:
    extends:
      file: ./compose.base.yml
      service: app
      
  db:
    extends:
      file: ./compose.base.yml
      service: db

  phpmyadmin:
    extends:
      file: ./compose.base.yml
      service: phpmyadmin

  livekit:
    extends:
      file: ./compose.base.yml
      service: livekit

  redis:
    extends:
      file: ./compose.base.yml
      service: redis

  egress:
    extends:
      file: ./compose.base.yml
      service: egress

  # ingress:
  #   extends:
  #     file: ./compose.base.yml
  #     service: ingress
  # ingress:
  #   extends:
  #     file: ./compose.base.yml
  #     service: ingress
  #   network_mode: host        # 👈 Use host networking
  #   # ports: []                 # 👈 Required: disable `ports` when using host mode
  #   # networks: []              # 👈 Required: disable Docker-managed networks


  # turnserver:
  #   extends:
  #     file: ./compose.base.yml
  #     service: turnserver

volumes:
  dev_db_data:
  dev_node_modules:

networks:
  dev_default:
    external: true