services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    image: bh-${NODE_ENV}
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - ${NODE_ENV}_default
    labels:
      - "traefik.enable=true"
      # HTTPS Route
      - "traefik.http.routers.${NODE_ENV}-app-secure.rule=${HOST}"
      - "traefik.http.routers.${NODE_ENV}-app-secure.entrypoints=websecure"
      - "traefik.http.routers.${NODE_ENV}-app-secure.middlewares=strip-${TAG}"
      - "traefik.http.routers.${NODE_ENV}-app-secure.tls.certresolver=myresolver"
      - "traefik.http.services.${NODE_ENV}-app.loadbalancer.server.port=3000"
 #     - "traefik.http.routers.${NODE_ENV}-app.middlewares=auth"
#      - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$sdARNjrF$$o5oY9am2uedUdHztBJUOn1"

      # HTTP Route
      - "traefik.http.routers.${NODE_ENV}-app.rule=${HOST}"
      - "traefik.http.routers.${NODE_ENV}-app.entrypoints=web"
      - "traefik.http.services.${NODE_ENV}-app.loadbalancer.server.port=3000"
      - "traefik.http.routers.${NODE_ENV}-app.middlewares=strip-${TAG}"
      - "traefik.http.middlewares.strip-${TAG}.stripPrefix.prefixes=/${TAG}"

    
  db:
    image: mysql:8.0.35
    restart: always
    networks:
      - ${NODE_ENV}_default
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_PORT: ${MYSQL_DB_PORT}
      MYSQL_HOST: ${MYSQL_DB_HOST}
    labels:
      - "traefik.enable=false"
    volumes:
      - ${NODE_ENV}_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
    ports:
      - "8091:80"
    networks:
      - ${NODE_ENV}_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=PathPrefix(`/db`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.middlewares=strip-db"
      - "traefik.http.middlewares.strip-db.stripprefix.prefixes=/db"

  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    ports:
      - "7880:7880"       # API / WebRTC signaling
      - "7881:7881"       # TCP fallback
      - "50000-60000:50000-60000/udp"  # Media relay ports
      - "3478:3478/udp"   # TURN UDP
      - "3478:3478/tcp"   # TURN TCP
      - "5349:5349/tcp"   # TURN TLS
      - "5349:5349/udp"   # TURN TLS UDP
    volumes:
      - ./livekit/config.yaml:/etc/livekit/config.yaml
    environment:
      - LIVEKIT_CONFIG=/etc/livekit/config.yaml
      - LIVEKIT_ANNOUNCE_IP="0.0.0.0"  # or your public IP


    # environment:
    #   # LIVEKIT_KEYS: "livekit-secret:supersecret"
    #   LIVEKIT_TURN_SECRET: "turn-secret"
    # # network_mode: "host"
    # networks:
    #   - ${NODE_ENV}_default
    # depends_on:
    #   redis:
    #     condition: service_started
    # volumes:
    #   - ./livekit/livekit.yaml:/etc/livekit.yaml

  redis:
    image: redis:7-alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    # network_mode: "host"
    networks:
      - ${NODE_ENV}_default
    volumes:
      - ./livekit/redis.conf:/etc/redis.conf

  egress:
    image: livekit/egress:latest
    restart: unless-stopped
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
    # network_mode: "host"
    networks:
      - ${NODE_ENV}_default
    volumes:
      - ./livekit/egress.yaml:/etc/egress.yaml
    cap_add:
      - CAP_SYS_ADMIN

  ingress:
    image: livekit/ingress:latest
    restart: unless-stopped
    environment:
      - INGRESS_CONFIG_FILE=/etc/ingress.yaml
    # network_mode: "host"
    networks:
      - ${NODE_ENV}_default
    volumes:
      - ./livekit/ingress.yaml:/etc/ingress.yaml

  # turnserver:
  #   image: coturn/coturn  # Or the actual image you're using
  #   command: turnserver -c /etc/turnserver.conf
  #   # network_mode: "host"
  #   restart: always
  #   networks:
  #     - ${NODE_ENV}_default
  #   ports:
  #     - "3478:3478/udp"  # UDP relay (default TURN UDP)
  #     - "3478:3478/tcp"  # TURN TCP (default)
  #     - "5349:5349/tcp"  # TURN TLS TCP
  #     - "5349:5349/udp"  # TURN TLS UDP (optional, if used)
  #   volumes:
  #     - ./livekit/turnserver.conf:/etc/turnserver.conf

