services:
  app:
    extends:
      file: ./compose.base.yml
      service: app
      
  db:
    extends:
      file: ./compose.base.yml
      service: db

  # phpmyadmin:
  #   extends:
  #     file: ./compose.base.yml
  #     service: phpmyadmin

volumes:
  dev_db_data:
  dev_node_modules:

networks:
  dev_default:
    external: true