FROM node:18-alpine

# Install pnpm
RUN apk add --no-cache git
RUN npm install -g pnpm

WORKDIR /app

COPY package*.json ./

# Install dependencies
RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]