FROM node:18-alpine

# Install pnpm
RUN apk add --no-cache git tzdata
RUN npm install -g pnpm

ARG TZ=Africa/Addis_Ababa
ENV TZ=$TZ

RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

COPY package.json ./
COPY pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]